the-virtual-brain/tvb-root

scientific_library/tvb/simulator/plot/phase_plane_interactive.py
scientific_library/tvb/simulator/plot/tools.py

Method set_axis_bgcolor is no longer in th API, now you have to use new method set_facecolor (matplotlib 3.1)

Change set_axis_bgcolor to new method set_facecolor

---

tvb_build/Jenkinsfile-Step1
tvb_build/docker/Dockerfile

Don't use cached repo if there is a new commit

Fix jenkins build

---

tvb_documentation/matlab/tvb_demo_region_rww.m
tvb_documentation/matlab/tvb_demo_two_epi.m
tvb_documentation/matlab/tvb_matlab.py

This should address [TVB-2586](https://req.thevirtualbrain.org/browse/TVB-2586) with the demos updates for Py3 & neotraits compat.

Fixes for MATLAB API

---

framework_tvb/tvb/adapters/simulator/simulator_adapter.py
framework_tvb/tvb/adapters/simulator/simulator_fragments.py
framework_tvb/tvb/core/entities/storage/datatype_dao.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py

set default simulation name pre-filled on the Burst page

TVB-2578 Default simulation name

---

framework_tvb/tvb/adapters/datatypes/db/time_series.py
framework_tvb/tvb/adapters/visualizers/brain.py
framework_tvb/tvb/adapters/visualizers/time_series_volume.py

TVB-2618 Visualizers with StateVariable wrong usage

---

framework_tvb/tvb/core/entities/model/model_datatype.py
framework_tvb/tvb/core/services/flow_service.py
framework_tvb/tvb/interfaces/web/controllers/project/project_controller.py
framework_tvb/tvb/interfaces/web/templates/jinja2/overlay.html

Add default on DataTypeMatrix.ndim field 
Add warning to be displayed in the web GUI

TVB-2619 DT Overlay not showing in web GUI when Adapter has errors in its filter

---

framework_tvb/tvb/adapters/simulator/monitor_forms.py
framework_tvb/tvb/core/services/simulator_serializer.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
framework_tvb/tvb/interfaces/web/templates/jinja2/project/upload_data_overlay.html
scientific_library/tvb/datatypes/sensors.py
scientific_library/tvb/simulator/monitors.py

So far I got rid of some if's by replacing them with methods for the sensor monitors that specify which class is needed for which sensors and surface type.

WIP TVB-2626

---

scientific_library/tvb/basic/config/profile_settings.py

TVB-2631 Fix keycloak login enabled flag

---

framework_tvb/AUTHORS
framework_tvb/MANIFEST.in
framework_tvb/MANIFEST_rest_client.in
tvb_build/package_for_pip.sh
tvb_build/tvb_build/third_party_licenses/packages_accepted.xml

TVB-2630 tvb-rest-client package

---

framework_tvb/tvb/adapters/visualizers/pse_isocline.py
framework_tvb/tvb/core/entities/model/model_operation.py

This fix makes Isocline Visualizer work. However, as I said in my TODO's: it should be extended to make it work for GID params as well.

TVB-2640:  Fix for Isocline Visualizer

---

dev_resources/docs/ReleaseProcedure
framework_tvb/setup_rest_client.py
framework_tvb/tvb/interfaces/rest/client/examples/launch_operation.py
tvb_build/deploy_with_keycloak/Dockerfile

- will release also tvb-framework 2.0.3a1

TVB-2655 Prepare release tvb-rest-client 2.0.3

---

framework_tvb/tvb/adapters/analyzers/metrics_group_timeseries.py
framework_tvb/tvb/adapters/simulator/monitor_forms.py
framework_tvb/tvb/adapters/simulator/noise_forms.py
framework_tvb/tvb/core/neotraits/forms.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
scientific_library/tvb/datatypes/cortex.py

I have done this without using a class.
I made a private method in SimulatorController which builds a list of the chosen variable names associated with their indexes and I give the names to the forms and the indexes to the monitor. The if condition in the fill_from_post in MonitorForm is because we only want that to be executed at loading, when we actually have variables of interest in the monitor, we don't need that when setting the parameters.

Fix model variables selection step

---

scientific_library/tvb/simulator/plot/base_plotter.py
scientific_library/tvb/simulator/plot/config.py
scientific_library/tvb/simulator/plot/head_plotter.py
scientific_library/tvb/simulator/plot/plotter.py
scientific_library/tvb/simulator/plot/power_spectra_interactive.py
scientific_library/tvb/simulator/plot/time_series_plotter.py
scientific_library/tvb/simulator/plot/timeseries_interactive.py
scientific_library/tvb/simulator/plot/utils.py

I moved back under tvb-scripts the configurations that are not related to figures.

HBP-75 Merge plotting from tvb-scripts

---

framework_tvb/tvb/adapters/simulator/monitor_forms.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/simulator_controller_test.py

I solved the new tests failing in SimulatorController, I made all interest variables being chosen by default for the monitors, I made Simulator with Raw Monitor being able to be launched (it just takes much time, so I tried with 100ms Simulation Length) and I added interest variables to TemporalAverage Monitor as well.

TVB-2551: Fixed everything that was written after the task has been reopened.

---

framework_tvb/tvb/adapters/visualizers/pse_discrete.py
framework_tvb/tvb/adapters/visualizers/pse_isocline.py
framework_tvb/tvb/core/entities/model/model_operation.py
framework_tvb/tvb/core/entities/transient/pse.py
framework_tvb/tvb/interfaces/web/controllers/burst/exploration_controller.py
framework_tvb/tvb/interfaces/web/controllers/flow_controller.py
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/pse_isocline/pse_isocline.js
framework_tvb/tvb/tests/framework/adapters/analyzers/fft_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/pse_test.py
framework_tvb/tvb/tests/framework/conftest.py
framework_tvb/tvb/tests/framework/core/base_testcase.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/exploration_controller_test.py

Extracted common code for PSE visualizers, to ensure they work on the same data and adjusted code afterwards.

TVB-2645  PSE Viewers

---

framework_tvb/setup_rest_client.py
framework_tvb/tvb/core/adapters/abcadapter.py
framework_tvb/tvb/interfaces/rest/client/examples/fire_simulation.py
framework_tvb/tvb/interfaces/rest/client/operation/operation_api.py
framework_tvb/tvb/interfaces/rest/client/tvb_client.py
framework_tvb/tvb/interfaces/rest/commons/dtos.py

Toni needs:
- a helper to launch an operation based on datatype_gid and algorithmDTO
- a way to access the algorithmDTO displayname from an OperationDTO

TVB-2662. Extend tvb-rest-client with helpers

---

tvb_build/Jenkinsfile-Windows
tvb_build/build_from_conda.py
tvb_build/docker/Dockerfile-Windows-build

Added Dockerfile and Jenkinfile which will be used to build the TVB-Distribution for Windows.

TVB-2527 TVB-Distribution Windows Build

---

framework_tvb/tvb/adapters/creators/local_connectivity_creator.py
framework_tvb/tvb/interfaces/web/controllers/common.py
framework_tvb/tvb/interfaces/web/controllers/spatial/local_connectivity_controller.py
framework_tvb/tvb/interfaces/web/templates/jinja2/spatial/equation_displayer.html

LocalConnectivity creator: 
- show a nice message, to inform the user what to do when missing Cortical Surfaces from the current project
- cleanup TODOs

TVB-2581: Improve LocalConnectivity creator

---

framework_tvb/tvb/adapters/creators/local_connectivity_creator.py
framework_tvb/tvb/adapters/visualizers/brain.py
framework_tvb/tvb/adapters/visualizers/surface_view.py
framework_tvb/tvb/core/entities/load.py
framework_tvb/tvb/core/entities/storage/datatype_dao.py
framework_tvb/tvb/core/services/user_service.py
framework_tvb/tvb/interfaces/web/controllers/spatial/base_spatio_temporal_controller.py
framework_tvb/tvb/interfaces/web/controllers/spatial/local_connectivity_controller.py
framework_tvb/tvb/interfaces/web/controllers/spatial/region_stimulus_controller.py
framework_tvb/tvb/interfaces/web/controllers/spatial/surface_stimulus_controller.py
framework_tvb/tvb/tests/framework/adapters/uploaders/csv_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/obj_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/tvb_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/zip_surface_importer_test.py
framework_tvb/tvb/tests/framework/conftest.py
framework_tvb/tvb/tests/framework/core/entities/transactional_test.py
framework_tvb/tvb/tests/framework/core/factory.py
framework_tvb/tvb/tests/framework/core/services/user_service_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/project_controller_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/simulator_controller_test.py

LC, Surface Stimulus and Region Stimulus pages throw generic errors when opened in  an empty project.
Instead we should show explicit error messages.
Fix some unit-tests

TVB-2581 Fix behavior of creators in TVB Web when launched in an empty project

---

framework_tvb/tvb/adapters/datatypes/db/graph.py
framework_tvb/tvb/adapters/uploaders/connectivity_measure_importer.py
framework_tvb/tvb/adapters/visualizers/surface_view.py
framework_tvb/tvb/adapters/visualizers/topographic.py
framework_tvb/tvb/core/entities/model/model_datatype.py
framework_tvb/tvb/interfaces/web/controllers/flow_controller.py
framework_tvb/tvb/tests/framework/adapters/uploaders/connectivity_measure_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/connectivity_zip_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/csv_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/projection_matrix_importer_test.py
framework_tvb/tvb/tests/framework/core/factory.py

add filters for visualisers + add ndim to fill_from_has_traits graph.py

TVB-2656 - Fix display for BCT visualisers

---

framework_tvb/tvb/core/entities/file/simulator/burst_configuration_h5.py
framework_tvb/tvb/interfaces/web/controllers/burst/dynamic_model_controller.py
framework_tvb/tvb/interfaces/web/controllers/burst/region_model_parameters_controller.py
framework_tvb/tvb/interfaces/web/static/js/bursts_dynamic.js
framework_tvb/tvb/interfaces/web/static/js/spatial/stimulus_region.js

Also, I missed the required=False flag in BurstConfigurationH5.

TVB-2617. Fix PhasePlane rendering

---

framework_tvb/tvb/core/entities/storage/project_dao.py
framework_tvb/tvb/core/services/project_service.py
framework_tvb/tvb/core/services/user_service.py
framework_tvb/tvb/interfaces/rest/client/tvb_client.py
framework_tvb/tvb/interfaces/rest/client/user/user_api.py
framework_tvb/tvb/interfaces/rest/server/facades/project_facade.py
framework_tvb/tvb/interfaces/rest/server/facades/user_facade.py
framework_tvb/tvb/interfaces/rest/server/resources/project/project_resource.py
framework_tvb/tvb/interfaces/rest/server/resources/rest_resource.py
framework_tvb/tvb/interfaces/rest/server/resources/user/user_resource.py
framework_tvb/tvb/interfaces/web/controllers/users_controller.py
framework_tvb/tvb/tests/framework/adapters/uploaders/mat_timeseries_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/networkx_importer_test.py
framework_tvb/tvb/tests/framework/adapters/uploaders/nifti_importer_test.py
framework_tvb/tvb/tests/framework/core/services/project_service_test.py
framework_tvb/tvb/tests/framework/core/services/user_service_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/project_controller_test.py

- Allow using different page sizes on retrieval of users 
* smaller page size for users management
* more for project members in web GUI and REST api
- when creating a new project (either from GUI or REST) always make the admin also a member

TVB-2674 and TVB-2667 Review users retrieval and project membership

---

tvb_build/package_for_pip.sh

https://jenkins.codemart.ro/view/TVB/job/TVB%20-%20Step1%20-%20ContribPack/

TVB-2525 tvb-contrib pip package

---

framework_tvb/tvb/adapters/datatypes/db/fcd.py
framework_tvb/tvb/adapters/datatypes/db/graph.py
framework_tvb/tvb/adapters/datatypes/db/region_mapping.py
framework_tvb/tvb/adapters/datatypes/db/structural.py
framework_tvb/tvb/adapters/datatypes/h5/connectivity_h5.py
framework_tvb/tvb/adapters/datatypes/h5/graph_h5.py
framework_tvb/tvb/adapters/datatypes/h5/patterns_h5.py
framework_tvb/tvb/adapters/datatypes/h5/sensors_h5.py
framework_tvb/tvb/adapters/visualizers/histogram.py
framework_tvb/tvb/adapters/visualizers/topographic.py
framework_tvb/tvb/core/adapters/abcadapter.py
framework_tvb/tvb/core/entities/file/simulator/burst_configuration_h5.py
framework_tvb/tvb/core/entities/file/simulator/monitor_h5.py
framework_tvb/tvb/core/entities/model/model_datatype.py
framework_tvb/tvb/tests/framework/datatypes/dummy_datatype_h5.py
scientific_library/tvb/datatypes/graph.py

The fix for the HistogramViewer consist of changes in `histogram.py` and `graph_h5.py` files only.
Rest of the changes in this PR are for similar problems, or reviewing Indexing classes.

TVB-2680 Fix Histogram Viewer

---

framework_tvb/tvb/adapters/datatypes/h5/time_series_h5.py
framework_tvb/tvb/adapters/visualizers/brain.py
framework_tvb/tvb/adapters/visualizers/surface_view.py
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/brain/view.html
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/commons/scripts/virtualBrain.js
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/commons/scripts/visualizers_commons.js

The Visualizer works now, the brain appears, but I just want to do two things before I consider it done:
1. It seems as those little visualizers in the right part don't work like in the demo. Sometimes they appear as I enter, sometimes they don't. I have to see what's there.
2. I was trying to make a general url for adapters(those which call invoke_adapter) cause there is already one for those with h5 and as you can see the new url that I added in JS and I would like to do that in case we want to move more methds there.

TVB-2651: Solved Brain Activity Visualizer Problem

---

framework_tvb/tvb/adapters/datatypes/h5/time_series_h5.py
framework_tvb/tvb/adapters/visualizers/brain.py
framework_tvb/tvb/adapters/visualizers/eeg_monitor.py
framework_tvb/tvb/adapters/visualizers/pearson_cross_correlation.py
framework_tvb/tvb/adapters/visualizers/pearson_edge_bundle.py
framework_tvb/tvb/adapters/visualizers/time_series.py
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/brain/internal_view.html
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/brain/portlet_preview.html
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/brain/view.html
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/commons/scripts/internalBrain.js
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/commons/scripts/virtualBrain.js
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/commons/scripts/visualizers_commons.js
framework_tvb/tvb/tests/framework/adapters/visualizers/brainviewer_test.py
scientific_library/contrib/tvb/contrib/scripts/datatypes/time_series.py
scientific_library/tvb/datatypes/time_series.py

We seem to have a broken functionality in TSRegion BrainActivity viewer (after recent fix for TSSurface same viewer).
Also some slow or complex code can be observed in these parts.

TVB-2651 Review BrainActivityViewer

---

framework_tvb/tvb/adapters/analyzers/wavelet_adapter.py
framework_tvb/tvb/core/neotraits/_h5accessors.py
framework_tvb/tvb/core/neotraits/_h5core.py
framework_tvb/tvb/tests/framework/conftest.py

- make range a dict and saving it as a json in the h5 so it can be saved

TVB-2695: Wavelet GUI input configuration

---

framework_tvb/tvb/adapters/analyzers/cross_correlation_adapter.py
framework_tvb/tvb/adapters/analyzers/fmri_balloon_adapter.py
framework_tvb/tvb/adapters/analyzers/fourier_adapter.py
framework_tvb/tvb/adapters/analyzers/node_coherence_adapter.py
framework_tvb/tvb/adapters/analyzers/node_complex_coherence_adapter.py

`small_ts.sample_period_unit = time_series_h5.sample_period_unit.load()`

TVB-2695 repeat wavelet fix for multiple analyzers

---

framework_tvb/tvb/adapters/analyzers/metrics_group_timeseries.py
framework_tvb/tvb/interfaces/web/controllers/burst/noise_configuration_controller.py
framework_tvb/tvb/tests/framework/adapters/analyzers/adapters_test.py
framework_tvb/tvb/tests/framework/adapters/analyzers/fft_test.py
framework_tvb/tvb/tests/framework/adapters/analyzers/timeseries_metrics_adapter_test.py
framework_tvb/tvb/tests/framework/adapters/creators/stimulus_creator_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/brainviewer_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/connectivityviewer_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/covarianceviewer_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/crosscoherenceviewer_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/crosscorelationviewer_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/eegmonitor_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/ica_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/sensorsviewer_test.py
framework_tvb/tvb/tests/framework/adapters/visualizers/time_series_test.py
framework_tvb/tvb/tests/framework/core/base_testcase.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/noise_configuration_controller_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/region_model_parameters_controller_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/simulator_controller_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/surface_model_parameters_controller_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/surface_stimulus_controller_test.py

Did some additional cleanup on unit-tests around this area

TVB-2700: Fixed noise configuration in case of Stochastic Integrators + Tests

---

framework_tvb/tvb/core/services/user_service.py
framework_tvb/tvb/interfaces/web/controllers/users_controller.py
framework_tvb/tvb/interfaces/web/static/js/keycloak.js
framework_tvb/tvb/interfaces/web/templates/jinja2/index.html
framework_tvb/tvb/interfaces/web/templates/jinja2/user/keycloak_config.html
framework_tvb/tvb/interfaces/web/templates/jinja2/user/login.html
framework_tvb/tvb/interfaces/web/templates/jinja2/user/profile.html
framework_tvb/tvb/interfaces/web/templates/jinja2/user/user_management.html

By default all keycloak users are validated. If an invalidated user attempts to login we will show an error message: "Your account is not validated. Please contact us at support@thevirtualbrain.org for more details". Keycloak users who will have the ADMINISTRATOR role assigned in the keycloak system will be able to validate/invalidate users.

HBP-81 Use the validate flag also for keycloak users.

---

framework_tvb/tvb/core/neotraits/forms.py
scientific_library/tvb/analyzers/ica.py

For the integer input validation I made the exact same thing as with floats. I saw there a TODO saying that we should raise an exception but I don't know what kind of exception so I just left it like that.
For ICA, I don't really know what those parameters mean, but based on their shapes, I deduced how they should be rearranged so the analyzer doesn't fail at launching. It works now, and the visualizer works as well.

TVB-2694  Integer input validation + part TVB-2728 ICA Fix

---

framework_tvb/tvb/core/entities/model/model_burst.py
framework_tvb/tvb/interfaces/web/controllers/common.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
framework_tvb/tvb/interfaces/web/static/js/bursts.js
framework_tvb/tvb/interfaces/web/templates/jinja2/burst/burst_history.html
framework_tvb/tvb/interfaces/web/templates/jinja2/burst/main_burst.html

To me it seems like it works as it should now, but I would appreciate some review.

TVB-2723: Review Copy Simulation Current Implementation

---

framework_tvb/tvb/interfaces/web/templates/jinja2/user/profile.html

HBP-80 Fix profile page when there is no role assigned for the user (but logged user is in the admins list)

HBP-80 Fix profile page when there is no role assigned for the user

---

framework_tvb/tvb/core/services/burst_service.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
framework_tvb/tvb/interfaces/web/static/js/bursts.js

I made the buttons invisible after launching, but the problem that I couldn't solve so far is that if you refresh the simulation before it finishes, the buttons will reappear. I would be happy hearing some suggestions for that :)

TVB-2722: Made buttons invisible after launching

---

framework_tvb/tvb/adapters/creators/stimulus_creator.py
framework_tvb/tvb/adapters/datatypes/db/simulation_history.py
framework_tvb/tvb/adapters/simulator/monitor_forms.py
framework_tvb/tvb/adapters/simulator/simulator_adapter.py
framework_tvb/tvb/config/init/datatypes_registry.py
framework_tvb/tvb/core/adapters/abcadapter.py
framework_tvb/tvb/core/adapters/inputs_processor.py
framework_tvb/tvb/core/entities/file/simulator/simulation_history_h5.py
framework_tvb/tvb/core/entities/file/simulator/view_model.py
framework_tvb/tvb/core/services/operation_service.py
framework_tvb/tvb/core/services/project_service.py
framework_tvb/tvb/core/services/simulator_serializer.py
framework_tvb/tvb/interfaces/web/controllers/project/project_controller.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
framework_tvb/tvb/interfaces/web/controllers/spatial/region_stimulus_controller.py
framework_tvb/tvb/interfaces/web/controllers/spatial/surface_model_parameters_controller.py
framework_tvb/tvb/interfaces/web/controllers/spatial/surface_stimulus_controller.py
framework_tvb/tvb/interfaces/web/templates/jinja2/project/details_operation_overlay.html
framework_tvb/tvb/tests/framework/adapters/analyzers/bct_test.py
framework_tvb/tvb/tests/framework/adapters/exporters/exporters_test.py
framework_tvb/tvb/tests/framework/adapters/simulator/simulator_adapter_test.py
framework_tvb/tvb/tests/framework/core/entities/file/datatypes/neotraits_h5_test.py
framework_tvb/tvb/tests/framework/core/factory.py
framework_tvb/tvb/tests/framework/core/services/project_structure_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/simulator_controller_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/surface_model_parameters_controller_test.py

Web GUI - Project - Operations - one finished operations with Success - Button Details - should show all changed input params different from the default.
- fix operation.parameters at initiate_prelaunch

WIP TVB-2687: Fix display of details for finished Operations in web GUI

---

framework_tvb/tvb/adapters/simulator/form_with_ranges.py
framework_tvb/tvb/adapters/simulator/noise_forms.py
framework_tvb/tvb/adapters/simulator/range_parameters.py
framework_tvb/tvb/adapters/simulator/simulator_fragments.py
framework_tvb/tvb/core/entities/model/model_operation.py
framework_tvb/tvb/core/entities/transient/range_parameter.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py

We have some wrong tvb.adapter dependencies in a few tvb.core classes

TVB-2663 Remove tvb.adapter dependency from model_operation

---

framework_tvb/tvb/core/entities/file/simulator/burst_configuration_h5.py
framework_tvb/tvb/core/services/operation_service.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/simulator_controller_test.py

The last one, which I marked with skip is not working yet. It says the file is not a valid ZIP file even though it's the one I export and it has the zip extension... I have to look why it says that.
86% of the lines are covered. Also, except the one for ZIP I want to write one for launching with branch and maybe a few more where more consecutive lines of code where not covered. Also, I would extract some common code in functions to make it nicer.

TVB-2549: Finish tests for Simulator Controller

---

framework_tvb/tvb/interfaces/rest/client/examples/fire_simulation.py
framework_tvb/tvb/interfaces/rest/client/operation/operation_api.py

We want a release of tvb-rest-client in order to accomodate the new rest server deploy at FRH.

TVB-2750. Adjust rest client code to server changes.

---

framework_tvb/tvb/interfaces/web/static/js/filters.js

After the recent changes there were some js errors in case no results were returned after filtering.

TVB-2428 Review filters.js

---

tvb_contrib/tvb/contrib/scripts/datatypes/projections.py
tvb_contrib/tvb/contrib/scripts/datatypes/time_series.py
tvb_contrib/tvb/contrib/scripts/datatypes/time_series_xarray.py
tvb_contrib/tvb/contrib/scripts/plot/plotter.py
tvb_contrib/tvb/contrib/scripts/service/head_service.py
tvb_contrib/tvb/contrib/scripts/service/time_series_service.py
tvb_contrib/tvb/contrib/scripts/utils/computations_utils.py
tvb_contrib/tvb/contrib/scripts/utils/data_structures_utils.py
tvb_contrib/tvb/contrib/scripts/utils/file_utils.py
tvb_contrib/tvb/contrib/scripts/utils/log_error_utils.py

HBP-87. Split changes/fixes done for tvb-contrib into a separate PR.

---

framework_tvb/tvb/adapters/analyzers/bct_adapters.py
framework_tvb/tvb/core/services/simulator_service.py
framework_tvb/tvb/tests/framework/adapters/analyzers/timeseries_metrics_adapter_test.py
framework_tvb/tvb/tests/framework/adapters/creators/stimulus_creator_test.py
framework_tvb/tvb/tests/framework/conftest.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/flow_controller_test.py
scientific_library/tvb/basic/config/environment.py

- fix FlowControllerTest
- correct run of BCT in Docker

TVB-2376 Fix unit-tests on FlowController.cancel_or_remove_operation

---

framework_tvb/tvb/adapters/visualizers/connectivity.py
framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/connectivity/main_connectivity.html

This is a corrected version of PR #230, which I unfortunately included extra commits in by mistake.

TVB-2753: Correctly split to left/right hemisphere

---

framework_tvb/tvb/core/neotraits/forms.py

On the base `Field` class, we have a `value` property that does not work correctly when float fields are zero. 
It ended up in returning a string '0' in the `view_stimulus` endpoint, thus the error.
I added an explicit check for this situation, as it is the quickest solution. But I believe this code needs a larger review. Maybe should be done together with the task [TVB-2669](https://req.thevirtualbrain.org/browse/TVB-2669), where we will also clean up the unnecessary `Field` classes.

TVB-2758. Ensure values of zero work for float fields

---

framework_tvb/tvb/adapters/datatypes/db/fcd.py
framework_tvb/tvb/adapters/datatypes/db/graph.py
framework_tvb/tvb/adapters/datatypes/db/mode_decompositions.py
framework_tvb/tvb/adapters/datatypes/db/spectral.py
framework_tvb/tvb/adapters/datatypes/db/temporal_correlations.py
framework_tvb/tvb/adapters/datatypes/db/time_series.py
framework_tvb/tvb/core/entities/model/model_datatype.py
framework_tvb/tvb/core/entities/storage/datatype_dao.py
framework_tvb/tvb/interfaces/rest/client/datatype/datatype_api.py
framework_tvb/tvb/interfaces/rest/client/examples/fire_simulation.py
framework_tvb/tvb/interfaces/rest/client/tvb_client.py
framework_tvb/tvb/interfaces/rest/commons/dtos.py
framework_tvb/tvb/interfaces/rest/commons/strings.py
framework_tvb/tvb/interfaces/rest/server/facades/datatype_facade.py
framework_tvb/tvb/interfaces/rest/server/resources/datatype/datatype_resource.py
framework_tvb/tvb/interfaces/rest/server/run.py

- FCD, CrossCorrelation, CorrelationCoefficients
- populate `labels_ordering` in analyzer adapters correctly

TVB-2731: REST API - provide extra information for various TS analysis results

---

framework_tvb/tvb/adapters/analyzers/fcd_adapter.py
framework_tvb/tvb/adapters/datatypes/db/mode_decompositions.py
framework_tvb/tvb/adapters/datatypes/db/spectral.py

These are inconsistencies found when testing the import/export of projects with different data.

TVB-2782. Small fixes after testing 

---

framework_tvb/setup.py
framework_tvb/tvb/core/services/backend_client_factory.py
framework_tvb/tvb/core/services/backend_clients/hpc_scheduler_client.py
framework_tvb/tvb/core/services/exceptions.py
framework_tvb/tvb/core/services/hpc_operation_service.py
framework_tvb/tvb/interfaces/web/controllers/hpc_controller.py
framework_tvb/tvb/interfaces/web/run.py
framework_tvb/tvb/tests/framework/core/services/hpc_scheduler_client_test.py
scientific_library/tvb/basic/config/settings.py

- Make pyunicore dependency optional, as it will be very seldom used only, and it does not exist on conda-forge

TVB-2764 conda-forge

---

scientific_library/tvb/simulator/simulator.py

Support for providing surface-based initial conditions.

TVB-2799 surface initial conditions

---

tvb_build/Jenkinsfile-TestsPG
tvb_build/Jenkinsfile-TestsSqLite

Removed always pull command because we don't push the test image to the docker registry anymore.

Review Jenkinsfile for tests

---

tvb_documentation/demos/multiple_stimuli.ipynb

Simplify further usage of a MultiStimuliRegion object in simulations.

TVB-2806. Update multiple_stimuli.ipynb

---

framework_tvb/tvb/adapters/datatypes/db/mapped_value.py
framework_tvb/tvb/config/init/datatypes_registry.py
framework_tvb/tvb/core/entities/file/simulator/datatype_measure_h5.py

Extracted this code as a separate PR because #244 also depends on it, and it would help to merge it sooner.

TVB-2747. Add DatatypeMeasure entity 

---

framework_tvb/tvb/adapters/simulator/simulator_adapter.py
scientific_library/tvb/simulator/monitors.py

I thought that this would be the best way to handle this problem, otherwise we would need an if at simulation launching to prevent it and another if in JS as well for displaying the message and that would disrupt the flow a bit.

TVB-2642: Show error message when period is bigger than simulation length

---

framework_tvb/tvb/adapters/analyzers/fmri_balloon_adapter.py
scientific_library/tvb/analyzers/fmri_balloon.py

Adjust tau_s and tau_f defaults and add them to GUI so they can be changed bu users

TVB-2780: Display more parameters in GUI for Balloon Analyzer

---

framework_tvb/tvb/core/entities/file/simulator/datatype_measure_h5.py
framework_tvb/tvb/core/entities/model/model_burst.py
framework_tvb/tvb/core/entities/model/model_operation.py
framework_tvb/tvb/core/entities/storage/datatype_dao.py
framework_tvb/tvb/core/neotraits/view_model.py
framework_tvb/tvb/core/services/burst_service.py
framework_tvb/tvb/core/services/import_service.py
framework_tvb/tvb/core/services/operation_service.py
framework_tvb/tvb/core/services/simulator_service.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py

This is a review for PR #257 that simplifies the procedure of export/import PSE by using only the ViewModel instead of adding an extra OperationGroupH5.
@adrian-dordea pls review and test various scenarios for this, you know better where the possible problems are.

TVB-2747. Review and simplify import/export of PSE.

---

framework_tvb/tvb/interfaces/web/static/js/region_associator.js
framework_tvb/tvb/interfaces/web/static/js/spatial/stimulus.js

Correctly sync between left and right side. Ensure data is sent in correct order to the server for the region stimulus page.

TVB-2788. Region Stimulus - click on a cube should toggle the corresponding checkbox

---

tvb_documentation/_static/additional_styles.css
tvb_documentation/_templates/layout.html
tvb_documentation/conf.py

Add aditional styles to index.html and _static folder

TZW-249: Add aditional styles to index.html and _static folder

---

framework_tvb/tvb/core/entities/file/files_helper.py
framework_tvb/tvb/core/entities/model/model_operation.py
framework_tvb/tvb/core/entities/storage/project_dao.py
framework_tvb/tvb/core/neocom/h5.py
framework_tvb/tvb/core/services/import_service.py
framework_tvb/tvb/core/services/operation_service.py
framework_tvb/tvb/core/services/simulator_service.py
framework_tvb/tvb/tests/framework/core/base_testcase.py
framework_tvb/tvb/tests/framework/core/services/project_service_test.py

add a new disk_size column to operation table for view_models and take them into account when calculating the project disk size

TVB-2767: Review flow for calculating and displaying the disk usage

---

tvb_documentation/_static/tvb_design/back_docs_subnav.svg
tvb_documentation/_static/tvb_design/icon_zoom.svg
tvb_documentation/_templates/layout.html

This is the last – **still invisible** – header content + asset update before we're ready to dump the CSS beta version of the big UI design update.

Docs website: updated site header + more graphic assets

---

tvb_documentation/_static/tvb_design/base.css

This is the first release of the complete website redesign, based on our design language from the TVB main website.
Further details are still in development but this PR delivers about 95% and improves the entire UX by a lot!

TZW-244: first release of complete website redesign

---

framework_tvb/tvb/core/services/operation_service.py
framework_tvb/tvb/interfaces/command/demos/importers/brain_tumor_connectivity_importer.py
framework_tvb/tvb/interfaces/command/lab.py

TVB-2834 Import tumor data from ebrains dataset

---

framework_tvb/tvb/interfaces/web/controllers/common.py
framework_tvb/tvb/interfaces/web/controllers/flow_controller.py
framework_tvb/tvb/interfaces/web/controllers/simulator_controller.py
framework_tvb/tvb/interfaces/web/static/js/bursts.js
framework_tvb/tvb/interfaces/web/templates/jinja2/burst/burst_history.html
framework_tvb/tvb/interfaces/web/templates/jinja2/simulator_fragment.html
framework_tvb/tvb/tests/framework/interfaces/web/jinja2_test.py

move branch button next to copy + creating new endpoint and make sure it works as current branch implementation

TVB-2538: Enhance Branch simulation use-case

---

scientific_library/tvb/simulator/simulator.py
scientific_library/tvb/tests/library/simulator/simulator_step_test.py

I propose a new method for computing the number of step.

number of step of the simulation

---

framework_tvb/tvb/core/entities/file/file_update_scripts/005_update_files.py
framework_tvb/tvb/core/entities/file/files_update_manager.py
scientific_library/Dockerfile
tvb_build/docker/Dockerfile-Windows-build
tvb_build/docker/Dockerfile-build
tvb_build/docker/Dockerfile-run
tvb_build/docker/Dockerfile-test
tvb_documentation/manuals/ContributorsManual/ContributorsManual.rst

update h5py + minor fix at migration + testing

TVB-2827: migrate h5py>3

---

framework_tvb/tvb/adapters/uploaders/tvb_importer.py
framework_tvb/tvb/core/neocom/_h5loader.py
framework_tvb/tvb/core/services/import_service.py

Error message in case of missing references, link in case datatype exists in a different project)

TVB-2853. Handle import of dts and dt groups in a similar manner

---

framework_tvb/tvb/adapters/exporters/TVBLinkedExporter.py
framework_tvb/tvb/adapters/exporters/abcexporter.py
framework_tvb/tvb/adapters/exporters/export_manager.py
framework_tvb/tvb/adapters/uploaders/tvb_importer.py
framework_tvb/tvb/core/adapters/abcadapter.py
framework_tvb/tvb/core/services/import_service.py
framework_tvb/tvb/core/services/operation_service.py
framework_tvb/tvb/interfaces/web/controllers/flow_controller.py
framework_tvb/tvb/interfaces/web/controllers/project/project_controller.py
framework_tvb/tvb/interfaces/web/templates/jinja2/project/details_datatype_overlay.html

Implement exporting DT with references from DT tab

TVB-2761: Export/Import of DT with related entities

---

tvb_documentation/_static/tvb_design/base.css

TVB-2824: fix super long method names on index page

Docs website: fix for width overflow on index page

---

framework_tvb/tvb/core/adapters/inputs_processor.py

TVB-2861: display inputs for all operations 

---

framework_tvb/tvb/adapters/exporters/TVBLinkedExporter.py
framework_tvb/tvb/adapters/exporters/export_manager.py
framework_tvb/tvb/adapters/exporters/tvb_export.py
framework_tvb/tvb/adapters/exporters/tvb_linked_export.py
framework_tvb/tvb/core/neotraits/_h5core.py
framework_tvb/tvb/tests/framework/adapters/exporters/exporters_test.py

TS import was failing on postgres if we export a TS (with links/ without links), then delete all projects, create a new project where we are trying to import this TS.

TVB-2858 Fix TS importing

---

framework_tvb/tvb/adapters/simulator/simulator_adapter.py
framework_tvb/tvb/adapters/simulator/simulator_fragments.py
framework_tvb/tvb/core/adapters/inputs_processor.py
framework_tvb/tvb/core/entities/file/simulator/view_model.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/simulator_controller_test.py

Fix CortexViewModel attributes display for simulations

Tvb 2854 - Operation overlay fix in case of surface simulations

---

framework_tvb/tvb/interfaces/web/templates/jinja2/visualizers/surface/surface_viewer_controls.html

remove region boundry box in case of no region mapping present

TVB-2859: Fix surface visualizer with region boundaries

---

framework_tvb/tvb/interfaces/web/templates/jinja2/simulator_fragment.html

Change the order of next and previous buttons on simulation page

TVB-2873: Keep Prev/Next buttons at the same position

---

framework_tvb/tvb/adapters/exporters/export_manager.py
framework_tvb/tvb/core/neocom/_h5loader.py
framework_tvb/tvb/core/neocom/h5.py
framework_tvb/tvb/core/services/backend_clients/hpc_scheduler_client.py
framework_tvb/tvb/core/services/simulator_service.py
framework_tvb/tvb/interfaces/web/controllers/burst/region_model_parameters_controller.py
framework_tvb/tvb/interfaces/web/controllers/simulator/simulator_controller.py
framework_tvb/tvb/interfaces/web/entities/context_simulator.py
framework_tvb/tvb/tests/framework/adapters/exporters/exporters_test.py
framework_tvb/tvb/tests/framework/core/neocom_test.py
framework_tvb/tvb/tests/framework/interfaces/web/controllers/simulator_controller_test.py

remove history_gid to fix import tor branched simulation

TVB-2874&TVB-2880: Fix import of branched simulation, export only view models

---

framework_tvb/tvb/adapters/visualizers/time_series_volume.py

This problem had two sources. The first one is what Paula described on the task and the second one was that prepare_view_region from region_volume_mapping is called twice and both times self was TimeSeriesVolumeVisualizer, but the second time it actually should have been different so the get_view_region from region_volume_mapping is called. That is why I changed the stored adapter in the launch method.

TVB-2887: Solved bug related to TimeSeriesVolumeVisualiser

---

.github/workflows/tests.yml
scientific_library/tvb/simulator/simulator.py

The methods I removed are now part of the [Model](https://github.com/the-virtual-brain/tvb-root/blob/master/scientific_library/tvb/simulator/models/base.py#L219) class

Remove duplicated code from simulator.py

---

framework_tvb/tvb/interfaces/web/templates/jinja2/user/profile.html

In these deployments we will set the correct settings manually.

HBP-155 Do not show settings menu entry when keycloak login is enabled

---

framework_tvb/tvb/adapters/uploaders/__init__.py
framework_tvb/tvb/adapters/uploaders/tumor_dataset_importer.py
framework_tvb/tvb/adapters/visualizers/pearson_cross_correlation.py
framework_tvb/tvb/config/init/alembic/versions/32d4bf9f8cab_update_db_002.py
framework_tvb/tvb/config/init/alembic/versions/ec2859bb9114_update_db_001.py
framework_tvb/tvb/core/adapters/abcuploader.py
framework_tvb/tvb/core/entities/model/model_datatype.py
framework_tvb/tvb/interfaces/web/controllers/project/project_controller.py
framework_tvb/tvb/interfaces/web/static/js/tumor_dataset_import.js
framework_tvb/tvb/interfaces/web/templates/jinja2/project/structure.html
framework_tvb/tvb/interfaces/web/templates/jinja2/project/viewoperations.html
framework_tvb/tvb/tests/framework/core/services/algorithm_service_test.py
scientific_library/tvb/basic/config/settings.py
tvb_storage/tvb/storage/h5/file/files_helper.py
tvb_storage/tvb/storage/storage_interface.py

So far I have extended the script written by Bogdan which was importing each connectivity. Now it also imports the FC.mat as a CorrelationCoefficients and HRF.csv file as a TS (with a good amound of hardcoding).
We need to store metadata in a JSON file and probably other files as well. For example in the HRF.csv file I suppose we only have the array_data matrix, but we also need a time matrix, so maybe another .csv file?

TVB-2911: Implement a BIDS importer

---

scientific_library/tvb/basic/neotraits/_attr.py
scientific_library/tvb/simulator/plot/phase_plane_interactive.py
tvb_contrib/tvb/contrib/scripts/datatypes/lookup_tables.py
tvb_contrib/tvb/contrib/simulator/models/brunel_wang.py
tvb_contrib/tvb/contrib/simulator/models/epileptor.py
tvb_contrib/tvb/contrib/simulator/models/generic_2d_oscillator.py
tvb_contrib/tvb/contrib/simulator/models/hindmarsh_rose.py
tvb_contrib/tvb/contrib/simulator/models/jansen_rit_david.py
tvb_contrib/tvb/contrib/simulator/models/larter.py
tvb_contrib/tvb/contrib/simulator/models/larter_breakspear.py
tvb_contrib/tvb/contrib/simulator/models/liley_steynross.py
tvb_contrib/tvb/contrib/simulator/models/morris_lecar.py
tvb_contrib/tvb/contrib/simulator/models/wong_wang.py
tvb_contrib/tvb/contrib/tests/model/model_test.py

Also, I fixed the obvious issues but I think someone else (who has worked on these) should also do a review.

TVB-2867: Fix models under tvb_contrib

---

tvb_documentation/manuals/UserGuide/DataExchange.rst

This RST hadn't been updated in a while, and some changes happened over the time in TVB's IN/OUT files.
This is a small correction to the Data Exchange descriptor.

TVB-2942: Update DataExchange.rst

---

tvb_storage/MANIFEST.in
tvb_storage/pytest.ini
tvb_storage/setup.py

I don't know if these changes are correct or if they are enough to solve this problem, but so far its the best I could come up with.

TVB-2949: Ensure tests are copied to the final tvb-storage package

---

scientific_library/tvb/simulator/plot/phase_plane_interactive.py
scientific_library/tvb/simulator/plot/power_spectra_interactive.py
scientific_library/tvb/simulator/plot/timeseries_interactive.py

Updated the code for plotters to use matplotlib.pyplot in place of pylab

TVB-2929:Updated pyplot in place of pylab

---

framework_tvb/tvb/core/services/import_service.py

…imported and delete related code.

TVB-2941: Show message when older projects are imported

---

scientific_library/tvb/tests/library/simulator/models_test.py

Fix error from the pull request : https://github.com/the-virtual-brain/tvb-root/pull/365

Change test for Wilson cowan

---

framework_tvb/tvb/adapters/visualizers/matrix_viewer.py
framework_tvb/tvb/core/neotraits/_h5core.py
tvb_documentation/RELEASE_NOTES

Fix typo in matrix_viewer. Fix tumor dataset launch bug. Update release notes.

TVB-2974. Fix bugs found after testing distribution.

---

framework_tvb/tvb/interfaces/web/static/js/genericTVB.js

Some action URLs were left in the old form (not web context)

TVB-2989 Fix urls without a context path

---

tvb_documentation/manuals/ContributorsManual/ContributorsManual.rst

Fix command line in documentation

---

framework_tvb/tvb/interfaces/rest/server/README.md

REST server doc update

---

scientific_library/tvb/simulator/monitors.py
scientific_library/tvb/tests/library/simulator/monitors_test.py

This address the library issue in TVB-3015.

Fix TVB-3015

---

tvb_documentation/demos/Demos.rst
tvb_documentation/demos/launching_bids_adapter.ipynb

We publish a notebook demonstrating how BIDS importer can be launched

TVB-2997 Add demo for launching BIDS importer

---

tvb_documentation/manuals/UserGuide/UserGuide.rst

I am grateful for this user guide but in general it needs a refresh. There are descriptions of nonexistent features, and several "todo" items being printed in the guide itself which confused me at first as a general reader. Do you need help with this?

Removed reference to "1.0"

---

tvb_framework/tvb/adapters/visualizers/phase_plane_interactive.py

If we modify the axis range in the tvb-web gui Phase Plane page for a model, these new values will be used as default ranges when this model is selected again.

TVB-2579 Fix state variables reset on changing models

---

tvb_framework/tvb/tests/framework/conftest.py
tvb_library/tvb/analyzers/fmri_balloon.py
tvb_library/tvb/basic/neotraits/_attr.py
tvb_library/tvb/basic/neotraits/_core.py
tvb_library/tvb/datatypes/time_series.py
tvb_library/tvb/simulator/integrators.py
tvb_library/tvb/simulator/monitors.py
tvb_library/tvb/simulator/noise.py
tvb_library/tvb/simulator/simulator.py
tvb_library/tvb/tests/library/basic/neotraits/neotraits_test.py

TVB-2878 Implement Deepcopy

---

tvb_documentation/demos/interacting_with_Allen.ipynb
tvb_framework/tvb/adapters/creators/allen_creator.py
tvb_library/tvb/analyzers/fmri_balloon.py

This task started as a bug found in a notebook using the allen_creator module. It proved to be in fact a problem from TVB, namely the usage of TVBEnums, which, in some cases, was incorrec.  So I fixed this problem everywhere I could find it.

TVB 3017. Fix allenSDK incompatible with TVB

---

.github/workflows/build.yml
.github/workflows/pg-tests.yml

TVB-2513 Address the setuptools issue in builds

---

tvb_build/Jenkinsfile-TVBRun
tvb_build/docker/Dockerfile-run
tvb_build/docker/requirements_group
tvb_build/hbp_openshift_deployer/tvb_deployer.yml
tvb_framework/requirements.txt
tvb_framework/tvb/interfaces/web/controllers/decorators.py
tvb_framework/tvb/interfaces/web/operation_openshift_assigner.py
tvb_storage/tvb/storage/h5/encryption/data_encryption_handler.py
tvb_storage/tvb/storage/kube/kube_notifier.py

Includes integration of kubernetes client for auth an k8s rest api calls

HBP-196. HBP-195. Fixes for OpenShift deploy

---

.github/workflows/lib-tests.yml
tvb_contrib/pytest.ini
tvb_contrib/tvb/contrib/tests/model/model_test.py
tvb_contrib/tvb/contrib/tests/scripts/time_series_test.py

This PR also includes [HBP-200](https://req.thevirtualbrain.org/browse/HBP-200), which relates to running the tvb-contrib tests inside a Github Actions workflow.
EDITED: This PR was waiting for #602 otherwise builds will fail with the recent inclusion of tvb-contrib tests in the Github Action

HBP-199. Move/add tests from tvb-multiscale to tvb-contrib

---

tvb_contrib/tvb/contrib/scripts/datatypes/time_series.py
tvb_contrib/tvb/contrib/scripts/datatypes/time_series_xarray.py
tvb_contrib/tvb/contrib/tests/scripts/time_series_test.py

This PR contains fixes for bugs in tvb-contrib, which were found when testing tvb-multiscale.

HBP-189 Fixes for tvb-multiscale in tvb-contrib

---

tvb_build/docker/requirements_group
tvb_framework/setup.py
tvb_framework/tvb/adapters/visualizers/connectivity_edge_bundle.py
tvb_framework/tvb/adapters/visualizers/histogram.py
tvb_framework/tvb/adapters/visualizers/pca.py
tvb_framework/tvb/adapters/visualizers/pearson_cross_correlation.py
tvb_framework/tvb/adapters/visualizers/pearson_edge_bundle.py
tvb_framework/tvb/adapters/visualizers/time_series.py
tvb_framework/tvb/interfaces/web/controllers/base_controller.py
tvb_library/tvb/basic/config/profile_settings.py

- fix serialization to JSON in viewers for labels read directly from H5
- fix `scikit-learn<=1.1.2` version due to problems in Windows distribution
- hide `SiibraCreator` due to KG query v3 problem

TVB-3039 Distribution fixes

---

tvb_framework/tvb/core/services/project_service.py
tvb_framework/tvb/interfaces/web/controllers/project/project_controller.py
tvb_framework/tvb/interfaces/web/static/js/genericTVB.js
tvb_framework/tvb/interfaces/web/templates/jinja2/project/editone.html
tvb_framework/tvb/tests/framework/core/services/project_service_test.py

- members can no longer edit project name of which they are not admin
- members can no longer delete projects of which they are not admin
- members have option to leave a project

TVB-3049: Add constraints for non admin project members

---

tvb_framework/tvb/interfaces/web/static/style/base.css

- when hovering over action buttons now a box shadow appears
- when clicking an action button now buttons slightly change appearance to provide visual feedback

TVB-3050: Add visual feedback on hover and click on action buttons

---

tvb_framework/tvb/adapters/creators/siibra_base.py
tvb_framework/tvb/adapters/creators/siibra_creator.py

Offer the users of TVB (especially those using the web app) more suggestive error messages when operations related to siibra do not work properly.

TVB-3053. Better Error handling

---

.github/workflows/lib-tests.yml
tvb_library/Pipfile
tvb_library/Pipfile.lock

This adds Pipfile for the tvb_library to improve the library setup process for development purposes with pipenv, addressing the issue of divergent requirements.txt, Dockerfiles, and CI build scripts (or maybe I'm not up to date on the latest?).  I don't think it's smart to merge changes to every CI script at once, so I just want to get the Pipfile in there first, start using it a bit, and later change the Dockerfile/CI scripts.

Add a tvb_library Pipfile

---

tvb_bin/run_migration.py
tvb_framework/tvb/config/profile_settings.py
tvb_library/tvb/basic/config/environment.py
tvb_library/tvb/basic/config/profile_settings.py

Add extra TRY on Env.is_distribution call, to avoid accidental installations of TVB_BIN
Get rid of EXTERNALS_FOLDER_PARENT property.

TVB-3067 Profile cleanup

---

tvb_library/tvb/basic/config/stored.py

TVB-2027 & TVB-2380 - Problems to launch TVB web server and DB connection in case of non-ascii characters in path

---

tvb_build/docker/requirements_group
tvb_framework/requirements.txt
tvb_framework/setup.py
tvb_framework/tvb/config/init/alembic/env.py
tvb_framework/tvb/core/entities/storage/datatype_dao.py
tvb_framework/tvb/core/entities/storage/operation_dao.py
tvb_framework/tvb/core/entities/storage/project_dao.py
tvb_framework/tvb/core/neotraits/db.py
tvb_framework/tvb/core/services/project_service.py
tvb_framework/tvb/tests/framework/core/services/project_structure_test.py

While migrating few new warnings from SQLAlchemy appeared, regarding aliases. Those are fixed also by this PR

HBP-219. Migrate code to SQLAlchemy > 2.0

---

tvb_framework/tvb/interfaces/web/controllers/burst/matjax.py
tvb_framework/tvb/interfaces/web/templates/jinja2/burst/dynamic.html
tvb_library/tvb/basic/neotraits/info.py

We reuse here code `from tvb.basic.neotraits.info import convert_rst_to_html` #639

TVB-3077 Improve equations display on PhasePlane page

---

tvb_deprecated/setup.py
tvb_library/setup.py

I already pushed this redirect into Pypi https://pypi.org/project/tvb/#history so you can test it from there directly.
This also adds Jan Fousek as author in `tvb-library`.

TVB-3078 Create a redirect in the Pypi package "tvb" towards "tvb-library"

---

tvb_library/tvb/datasets/tvb_data.py
tvb_library/tvb/datasets/zenodo.py
tvb_library/tvb/datatypes/local_connectivity.py
tvb_library/tvb/datatypes/projections.py
tvb_library/tvb/datatypes/region_mapping.py
tvb_library/tvb/datatypes/sensors.py
tvb_library/tvb/datatypes/surfaces.py
tvb_library/tvb/tests/library/datasets/TVBZenodoDataset_test.py

follow up of #675 . Fixed the errors (on local test environment), lets see if CI is happy or not.

Framework to download entities from Zenodo [PR No.2 ]

---

.github/workflows/build.yml
.github/workflows/lib-tests.yml
.github/workflows/notebooks.yml
.github/workflows/pg-tests.yml
.github/workflows/win-tests.yml

add missing `:` to the github workflow files.

---

tvb_build/docker/requirements_group
tvb_framework/requirements.txt
tvb_framework/setup.py
tvb_framework/tvb/adapters/visualizers/phase_plane_interactive.py

changed contour function from phase plane so it would work with a newer version of matplotlib(version==3.8.3)

EBR-39: change contour function from phase plane

---

tvb_documentation/demos/siibra_tvb_api.ipynb
tvb_framework/tvb/adapters/datatypes/db/local_connectivity.py
tvb_framework/tvb/tests/framework/conftest.py
tvb_storage/README.rst

EBR-40 Small adjustments before release 2.9

---

tvb_documentation/index.rst
tvb_documentation/manuals/ContributorsManual/ContributorsManual.rst

Where we mention Pypi we want also Anaconda to be mentioned

EBR-77: mention Anaconda distribution in docs

---

tvb_framework/tvb/interfaces/web/controllers/settings_controller.py

This was tested on:
- Mac Distribution
- Linux Distribution
- Windows Distribution
- Windows and Linux in py-charm (dev mode)

EBR-51 Fix startup of tvb web
